# Generated by Django 2.2.1 on 2019-05-06 19:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20190502_2243'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('get_visible', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='date_expires',
            field=models.DateField(),
        ),
    ]
