version: "3.7"

volumes:
  postgres_data:
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSRGRES_PASS: example123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
