# Generated by Django 2.2.1 on 2019-06-02 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.ManyToManyField(blank=True, null=True, related_name='guest_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
