# Generated by Django 2.2.1 on 2019-06-08 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0011_auto_20190602_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='observed_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
