# Generated by Django 2.2.1 on 2019-06-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_auto_20190609_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_expires',
            field=models.DateField(verbose_name='Data wygaśnięcia'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='room',
            name='gift',
            field=models.CharField(max_length=50, verbose_name='Cel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='room',
            name='receiver',
            field=models.CharField(max_length=50, verbose_name='odbiorca'),
        ),
        migrations.AlterField(
            model_name='room',
            name='to_collect',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Do zebrania'),
        ),
        migrations.AlterField(
            model_name='room',
            name='visible',
            field=models.BooleanField(verbose_name='Widoczny dla wszystkich?'),
        ),
    ]
