# Generated by Django 2.2.1 on 2019-06-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_auto_20190613_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
