# Generated by Django 2.2 on 2019-07-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_auto_20190619_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'get_latest_by': ['date'], 'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='room',
            name='gift_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Opis'),
        ),
    ]
