# Generated by Django 2.2 on 2019-07-04 19:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_auto_20190703_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateField(default=datetime.date(2019, 4, 15)),
        ),
        migrations.AlterField(
            model_name='room',
            name='gift_url',
            field=models.URLField(blank=True, verbose_name='Adres internetowy celu'),
        ),
    ]
