# Generated by Django 2.2 on 2019-07-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_auto_20190704_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
