# Generated by Django 2.2.1 on 2019-06-11 18:26

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_thread'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('visible', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
        migrations.AddField(
            model_name='thread',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Thread'),
        ),
    ]
