# Generated by Django 2.2.1 on 2019-06-11 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20190611_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.Thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.Post'),
        ),
    ]
