# Generated by Django 2.2.1 on 2019-06-17 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20190617_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='likes',
            field=models.IntegerField(choices=[(1, 'like'), (0, 'no_opinion'), (-1, 'dislike')], default=0),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='forum.Thread'),
        ),
    ]
