# Generated by Django 2.2.1 on 2019-06-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20190617_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='likes',
            field=models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')]),
        ),
    ]
